name: litgame_telegram_bot
description: litgame telegram bot
version: 2.0.0
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  meta: ^1.7.0
  teledart_app: 1.0.0-dev.3
  parse_server_sdk: ^3.1.0
#  dartis: ^0.5.0
#  redis: ^2.0.0
  litgame_client:
    git: https://github.com/litgame/rest-client.git


dev_dependencies:
  test: ^1.17.10
  pedantic: ^1.11.1
